config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  
  scope module: :user do
    resources :notifications, only: :index do
      delete 'notifications/destroy_all' => 'notifications#destroy_all'
    end
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/my_page/:id' => 'users#show', as: :my_page
    get '/information/edit' => 'users#edit'
    patch '/information' => 'users#update'
    get '/unsubscribe' => 'users#unsubscribe'
    patch '/withdraw' => 'users#withdraw'
    
    resources :reviews, only:[:index]
  end
  
  get '/books/search' => 'books#search'
  resources :books, only: [:new, :create, :update, :index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy], module: :user do
      resource :favorites, only: [:create, :destroy]
      get 'favorites' => 'reviews#favorites', as: "review_favorites"
      resources :review_comments, only: [:create, :destroy]
    end
  end
  
  
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/controllers/admin/reviews_controller.rb
  class Admin::ReviewsController < ApplicationController
    
    def index
      @reviews = Review.all.page(params[:page]).per(10)
    end
    
    def show
      @review = Review.find(params[:id])
    end
    
    def edit
      @review = Review.find(params[:id])
    end
    
    def update
      @review = Review.find(params[:id])
      @review.update(review_params)
    redirect_to admin_review_path(@review.id)
    end
    
    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to admin_reviews_path
    end
    
    private
    
    def review_params
      params.require(:review).permit(:title, :content, :star)
    end
    
  end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end
  
  def create
    @book = Book.find(params[:book_id])
    @review = current_user.reviews.new(review_params)
    @review.book_id = @book.id
    @review.save
    redirect_to reviews_path
  end

  def index
    user = User.find_by(id: params[:user_id]) || current_user
    @reviews = user.reviews.page(params[:page]).per(10)
  end
  
  def favorites
    @book = Book.find(params[:book_id])
    @favorites = Favorite.where(review_id: params[:review_id])
  end

  def edit
    @review = Review.find(params[:id])
    @book = Book.find(params[:book_id])
  end
  
  def update
    @review = Review.find_by(params[:id])
    @review.update(review_params)
    redirect_to reviews_path
  end
  
  def destroy
    @book = Book.find(params[:id])
    @review = Review.find_by(params[:id])
    @review.destroy
    redirect_to reviews_path
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :content, :star)
  end
  
  def ensure_correct_user
    review = Review.find(params[:id])
    if review.user != current_user
      redirect_to reviews_path
    end
  end
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/admin/reviews/edit.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3><%= @review.user.name %>さんのレビュー編集</h3>
      </div>
      <div class="text">
        <%= form_with model: @review, url: admin_review_path(@review.id), method: :patch do |f| %>
          <div class="form_group">
            <br><%= f.label :レビュータイトル %>
            <br><%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form_group">
            <br><%= f.label :レビュー内容 %>
            <br><%= f.text_field :content, class: "form-control" %>
          </div>
          <div class="form-group">
            <br><%= f.label :star, '評価 ', class: 'col-md-3 col-form-label' %>
            <div id="star"></div>
          </div>
          <script>
            $('#star').empty();
            $('#star').raty({
              size    : 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              scoreName: 'review[star]',　
              half: false,
            });
          </script>
          <div class="form_group">
          <br><%= f.submit "編集を更新", class: "btn btn-outline-primary rounded-pill" %>
        <% end %>
        <%= link_to "削除", admin_review_path(@review.id),  method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-danger rounded-pill" %>
      </div>
    </div>
  </div>

app/views/admin/reviews/index.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3>レビュー一覧</h3>
      </div>
      <div class="text-center">
        <% @reviews.each do |review| %>
          <div class="row mb-3 border-bottom p-2 border-opacity-75">
            <div class="col-md-7 mx-auto">
              <div class="row">
                <div class="col-md-12 text-start">
                  <%= image_tag review.user.get_profile_image(50, 50) %>
                  <%= link_to admin_review_path(review.id) do %>
                    <%= review.user.name %>
                  <% end %>
                  <h5 class="pt-3"><%= review.title %></h5>
                  <div id="star_<%=review.id %>"></div>
                  <div class="pt-2">
                    <%= simple_format(review.content) %>
                  </div>
                  <script>
                    $('#star_<%=review.id %>').empty();
                    $('#star_<%=review.id %>').raty({
                      size    : 36,
                      starOff: '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      score: <%= review.star %>,　
                      half: false,
                      readOnly: true
                    });
                  </script>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @reviews %>
      </div>
    </div>
  </div>

app/views/admin/reviews/show.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3>レビュー詳細画面</h3>
      </div>
          <div class="text-center">
        <table class="table">
          <tr>
            <th>ユーザー画像</th>
            <br><td><%= image_tag @review.user.get_profile_image(100, 100), class: "profile-img" %></td>
          </tr>
          <tr>
            <th>ユーザー名</th>
            <td><%= @review.user.name %></td>
          </tr>
          <tr>
            <th>レビュータイトル</th>
            <td><%= @review.title %></td>
          </tr>
          <tr>
            <th>レビュー内容</th>
            <td><%= @review.content %></td>
          </tr>
          <tr>
            <th>レビュー評価</th>
            <td><div id="star_<%= @review.id %>"></div></td>
          </tr>
        </table>
        <script>
          $('#star_<%= @review.id %>').empty();
          $('#star_<%= @review.id %>').raty({
            size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            score: <%= @review.star %>,　
            half: false,
            readOnly: true
          });
        </script>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <p class="text-center">
      <%= link_to "編集する", edit_admin_review_path(@review.id), class: 'btn btn-outline-secondary btn-sm m-3' %>
    </p>
  </div>