config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  
  scope module: :user do
    resources :notifications, only: :index do
      delete 'notifications/destroy_all' => 'notifications#destroy_all'
    end
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/my_page/:id' => 'users#show', as: :my_page
    get '/information/edit' => 'users#edit'
    patch '/information' => 'users#update'
    get '/unsubscribe' => 'users#unsubscribe'
    patch '/withdraw' => 'users#withdraw'
    
    resources :reviews, only:[:index]
  end
  
  get '/books/search' => 'books#search'
  resources :books, only: [:new, :create, :update, :index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy], module: :user do
      resource :favorites, only: [:create, :destroy]
      get 'favorites' => 'reviews#favorites', as: "review_favorites"
      resources :review_comments, only: [:create, :destroy]
    end
  end
  
  
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/user.rb
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
    
    has_many :reviews, dependent: :destroy
    has_many :reviewed_books, through: :reviews, source: :book
    has_many :favorites, dependent: :destroy
    has_many :favorite_reviews, through: :favorite, source: :review
    has_many :user_books, dependent: :destroy
    has_many :books, through: :user_books
    has_many :review_comments, dependent: :destroy
    
    # 通知を送ったユーザー、通知を送られたユーザー
    has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
    has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
    
    has_one_attached :profile_image
    
    
    validates :name, presence: true, length: { minimum: 2, maximum: 50 }
    validates :introduction, length: { maximum: 255 }
    
    def get_profile_image(width, height)
      if !profile_image.attached?
        file_path = Rails.root.join('app/assets/images/default-image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [width, height]).processed
    end
    
    def self.guest
      find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "ゲストユーザー"
      end
    end
  end

app/controllers/admin/reviews_controller.rb
  class Admin::ReviewsController < ApplicationController
    
    def index
      @reviews = Review.all.page(params[:page]).per(10)
    end
    
    def show
      @review = Review.find(params[:id])
    end
    
    def edit
      @review = Review.find(params[:id])
    end
    
    def update
      @review = Review.find(params[:id])
      @review.update(review_params)
    redirect_to admin_review_path(@review.id)
    end
    
    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to admin_reviews_path
    end
    
    private
    
    def review_params
      params.require(:review).permit(:title, :content, :star)
    end
    
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_deleted)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
  class User::FavoritesController < ApplicationController
    before_action :authenticate_user!
    
    def create
      @review = Review.find(params[:review_id])
      favorite = current_user.favorites.new(review_id: @review.id)
      favorite.save
      @review.create_notification_favorite(current_user)
    end
    
    def destroy
      @review = Review.find(params[:review_id])
      favorite = current_user.favorites.find_by(review_id: @review.id)
      favorite.destroy
    end
  end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/notifications_controller.rb
  class User::NotificationsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @notifications = current_user.passive_notifications
      @notifications.where(checked: false).each do |notification|
        notification.update_attribute(:checked, true)
      end
    end
     
    def destroy_all
      @notifications = current_user.passive_notifications.destroy_all
      redirect_to notifications_path
    end
  end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_up_path_for(resource)
    my_page_path(resource)
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/review_comments_controller.rb
  class User::ReviewCommentsController < ApplicationController
    
    def create
      @book = Book.find(params[:book_id])
      @review = Review.find(params[:review_id])
      @review_comment = current_user.review_comments.new(review_comment_params)
      @review_comment.review_id = @review.id
      @review_comment.save
      @review_comments = @review.review_comments
      @review.create_notification_comment(current_user, @review_comment.id)
      respond_to :js
    end
    
    def destroy
      @review = Review.find(params[:review_id])
      @review_comment = ReviewComment.find(params[:id])
      @review_comment.destroy
    end
    
    private
    
    def review_comment_params
      params.require(:review_comment).permit(:comment).merge(user_id: current_user.id)
    end
  end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end
  
  def create
    @book = Book.find(params[:book_id])
    @review = current_user.reviews.new(review_params)
    @review.book_id = @book.id
    @review.save
    redirect_to reviews_path
  end

  def index
    user = User.find_by(id: params[:user_id]) || current_user
    @reviews = user.reviews.page(params[:page]).per(10)
  end
  
  def favorites
    @book = Book.find(params[:book_id])
    @favorites = Favorite.where(review_id: params[:review_id])
  end

  def edit
    @review = Review.find(params[:id])
    @book = Book.find(params[:book_id])
  end
  
  def update
    @review = Review.find_by(params[:id])
    @review.update(review_params)
    redirect_to reviews_path
  end
  
  def destroy
    @book = Book.find(params[:id])
    @review = Review.find_by(params[:id])
    @review.destroy
    redirect_to reviews_path
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :content, :star)
  end
  
  def ensure_correct_user
    review = Review.find(params[:id])
    if review.user != current_user
      redirect_to reviews_path
    end
  end
  
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]
  
  def after_sign_in_path_for(resource)
    my_page_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to my_page_path(user), notice: 'guestuserでログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  protected
  # 退会しているかを判断するメソッド
  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted == true
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  
  def show
    @user = User.find(params[:id])
    @books = @user.user_books.all
    @book_read = @user.user_books.where(is_read: true)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to my_page_path(@user.id), notice: 'ユーザー情報を保存しました'
    else
      render :edit
    end
  end
  

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: '退会処理が完了しました'
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_deleted)
  end
  
  def ensure_guest_user
    @user = current_user
    if @user.name == "ゲストユーザー"
      redirect_to my_page_path(current_user), notice: "ゲストユーザーはプロフィール編集はできません"
    end
  end
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/notifications_helper.rb
  module User::NotificationsHelper
    def unchecked_notificatons
      @notifications = current_user.passive_notifications.where(checked: false)
    end
  end

app/views/user/reviews/edit.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3 class="mb-4 fw-bold">レビュー編集</h3>
         <%= form_with model: @review, url: book_review_path, method: :patch do |f| %>
          <div class="form-group">
            <br><%= f.label :title, 'タイトル' %>
            <%= f.text_field :title, placeholder: "感想のタイトル", class: 'form-control' %>
          </div>
          <div class="form-group">
            <br><%= f.label :content, '内容' %>
            <%= f.text_area :content, placeholder: "本の感想", class: 'form-control' %>
          </div>
          <div class="form-group">
            <br><%= f.label :star, '評価 ', class: 'col-md-3 col-form-label' %>
            <div id="star_<%=@review.id %>"></div>
          </div>
          <div class="form-group text-center">
              <%= f.submit "編集を更新する", class: "btn btn-outline-success my-3" %>
          </div>
          <div class="text-center">
            <%= link_to "戻る", reviews_path, class: "btn btn-outline-primary my-3" %>
          </div>
          <script>
            $('#star_<%=@review.id %>').empty();
            $('#star_<%=@review.id %>').raty({
              size    : 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              score: <%= @review.star %>,　
              scoreName: 'review[star]',
              half: false,
            });
          </script>
        <% end %>
      </div>
    </div>
  </div>

app/views/user/reviews/favorites.html.erb
   <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3 class="mb-4 mt-4 fw-bold"><%= @book.title %>のレビューにいいねした人</h3>
        <% @favorites.each do |favorite| %>
          <div class="row mb-3 border-bottom p-2 border-opacity-75">
            <div class="row">
              <div class="col-md-3">
                <%= image_tag favorite.user.get_profile_image(100, 100) %>
              </div>
              <div class="col-md-6 pt-4">
                <%= link_to my_page_path(favorite.user) do %>
                  <%= favorite.user.name %>
                <% end %>
              </div>
              <%= simple_format(favorite.user.introduction) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/user/reviews/index.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5 text-center">
      <div class="row">
        <h3 class="mb-4 fw-bold">マイレビュー</h3>
        <% @reviews.each do |review| %>
          <div class="row mb-3 border-bottom p-2 border-opacity-75">
            <div class="col-md-7 mx-auto">
              <div class="row">
                <div class="col-md-6 text-center">
                  <%= image_tag review.book.image_url %>
                </div>
                <div class="col-md-6 text-start">
                    <div class="text-end">
                      <% if review.user == current_user %>
                        <%= link_to book_review_path(id: review.book.id, book_id: review.book_id),  method: :delete, 
                        data: { confirm: '本当に消しますか？' }, class: "delete_link" do %>
                          <i class="fas fa-times"></i>
                        <% end %>
                      <% end %>
                    </div>
                  <h4><%= review.book.title %></h4>
                  <p><%= review.book.author %></p>
                  <h5 class="pt-3"><%= review.title %></h5>
                  <div id="star_<%=review.id %>"></div>
                  <div class="pt-2">
                    <div class="border border-dark p-2 border-opacity-25">
                      <%= simple_format(review.content) %>
                    </div>
                  </div>
                  <div class="text-end pt-1">
                    <% if review.user == current_user %>
                      <i class="fas fa-pencil-alt"></i>
                      <%= link_to "編集する", edit_book_review_path(id: review.id, book_id: review.book_id) %> | 
                      <%= link_to "詳細画面に戻る", book_path(review.book.id) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <script>
            $('#star_<%=review.id %>').empty();
            $('#star_<%=review.id %>').raty({
              size    : 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              score: <%= review.star %>,　
              half: false,
              readOnly: true
            });
          </script>
        <% end %>
        <%= paginate @reviews %>
      </div>
    </div>
  </div>

app/views/user/reviews/new.html.erb
  <div class="row-lg-8 main-top">
    <div class="col-sm-12 col-md-12 col-lg-8 mx-auto p-5">
      <div class="row">
        <h3>レビューフォーム</h3>
      </div>
      <%= form_with model: Review.new, url: book_reviews_path(@book), local: true do |f| %>
        <div class="form-group">
          <br><%= f.label :title, 'タイトル' %>
          <%= f.text_field :title, placeholder: "感想のタイトル", class: 'form-control' %>
        </div>
        <div class="form-group">
          <br><%= f.label :content, '内容' %>
          <%= f.text_area :content, placeholder: "本の感想", class: 'form-control' %>
        </div>
        <div class="form-group">
          <br><%= f.label :star, '評価 ', class: 'col-md-3 col-form-label' %>
          <div id="star"></div>
        </div>
        <script>
          $('#star').empty();
          $('#star').raty({
            size    : 36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            scoreName: 'review[star]',　
            half: false,
          });
        </script>
        <%= f.submit 'レビューを投稿', class: "btn btn-outline-success my-3" %>
      <% end %>
    </div>
  </div>

app/views/user/reviews/show.html.erb
<h1>User::Reviews#show</h1>
<p>Find me in app/views/user/reviews/show.html.erb</p>